document.write(
     '<div class="row darkgrey">' 
    +    '<div class="column fourth mid footer">' 
    +       '<h2>Website Links:</h2>' 
    +        '<p><a href="#">Participating Cities</a></p>' 
    +        '<p><a href="#">Mobile Reporting App</a></p>' 
    +        '<p><a href="#">See Nearby Hazards</a></p>' 
    +        '<p><a href="#">Create a Report</a></p>' 
    +        '<p><a href="#">API and Integrations</a></p>' 
    +    '</div>' 
    +    '<div class="column fourth mid footer">' 
    +        '<h2>-</h2>' 
    +        '<p><a href="./faq.html">FAQ</a></p>'
    +        '<p><a href="#">Contact Us</a></p>'
    +        '<p><a href="#">About Cima</a></p>'
    +        '<p><a href="#">Cima for Cities</a></p>'
    +    '</div>'
    +    '<div class="column fourth mid footer">'
    +        '<h2>Author:</h2>'
    +        '<h3>Eric J. Shoemaker</h3>'
    +        '<h3>Undergraduate Research Assistant at Marshall University</h3>'
    +        '<h4>Contact: shoemaker30@live.marshall.edu</h4>'
    +        '<h4>Github: shoemaker30</h4>'
    +    '</div>'
    +'</div>'
);