document.write(
     '<div class="row darkgrey">' 
    +    '<div class="column fourth footer">' 
    +       '<h2>Webpages:</h2>' 
    +        '<p><a href="/cimapp/CIMA-WebsitePages/info/cities">Participating Cities</a></p>' 
    +        '<p><a href="./mobile">Mobile Reporting App</a></p>' 
    +        '<p><a href="./report/view-nearby-reports.html">See Nearby Hazards</a></p>' 
    +        '<p><a href="./report/create.html">Create a Report</a></p>' 
    +        '<p><a href="./api">API and Integrations</a></p>' 
    +    '</div>' 
    +    '<div class="column fourth footer">' 
    +        '<h2>-</h2>' 
    +        '<p><a href="info/faq.html">FAQ</a></p>'
    +        '<p><a href="../contact">Contact Us</a></p>'
    +        '<p><a href="../info/about">About Cima</a></p>'
    +        '<p><a href="./webapp">Cima for Cities</a></p>'
    +    '</div>'
    +    '<div class="column fourth footer desktop-only">'
    +        '<h2>Author:</h2>'
    +        '<h3>Eric J. Shoemaker</h3>'
    +        '<h3>Undergraduate Research Assistant at Marshall University</h3>'
    +        '<h4>Contact:<br>shoemaker30@live.marshall.edu</h4>'
    +        '<h4>Github:<br>shoemaker30</h4>'
    +    '</div>'
    +'</div>'
);